blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$',
        views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page,name='edit_page'),
    url(r'^edit/action$', views.edit_action,name='edit_action'),

]

myDjango/urls.py
from django.contrib import admin
from django.conf.urls import url,include
# import blog.views as bv

urlpatterns = [
    url('admin/', admin.site.urls),
    # url('blog/', bv.index),
    url(r'^blog/', include('blog.urls',namespace='blog')),
]

blog/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.

class Article(models.Model):
    objects = None
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/views.py
# from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse

from . import models


def index(request):
    # return HttpResponse('hello world')
    # article = models.Article.objects.get(id=1)
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'hello': 'hello blog', 'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(id=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(id=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'hello': 'hello blog', 'articles': articles})
    article = models.Article.objects.get(id=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Article Page</title>
</head>
<body>
    <h1>{{article.title}}</h1>
    <br>
    <h3>{{article.content}}</h3>
    <br>
    <br>
    <a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Page</title>
</head>

<body>
    <form action="{% url 'blog:edit_action' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="article_id" value="{{article.id | default:'0'}}">
        <label>
            文章标题 <input type="text" name="title" value="{{article.title}}">
        </label>
        <br>
        <label>
            文章内容
            <textarea name="content" rows="10" cols="30">{{article.content}}</textarea>
        </label>
        <br>
        <input type="submit" name="提交">
    </form>
</body>

</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Page List</title>
</head>

<body>

    <a href="{% url 'blog:edit_page' '0' %}"><h2>新文章</h2></a> 
    <!-- <h2>This is Blog</h2>
    <h2>{{hello}}</h2> -->
    <!-- <h1>{{article.title}}</h1>
    <p>{{article.content}}</p> -->

    {% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
    <br>
    {% endfor %}


</body>

</html>